inline double g_cartesian_00(double x, double y, double z, double t) { return (pow(x, 2)*pow(z, 2)*(sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*pow(pow(x, 2) + pow(y, 2) + pow(z, 2), 3.0/2.0) + pow(x, 2)*(pow(x, 2) + pow(y, 2))*pow(pow(x, 2) + pow(y, 2) + pow(z, 2), 2) + pow(y, 2)*(sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*pow(pow(x, 2) + pow(y, 2) + pow(z, 2), 5.0/2.0))/((pow(x, 2) + pow(y, 2))*(sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*pow(pow(x, 2) + pow(y, 2) + pow(z, 2), 5.0/2.0)); }
inline double g_cartesian_01(double x, double y, double z, double t) { return 2*x*y*sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2))/(pow(x, 4) + 2*pow(x, 2)*pow(y, 2) + 2*pow(x, 2)*pow(z, 2) - 2*pow(x, 2)*sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) + pow(y, 4) + 2*pow(y, 2)*pow(z, 2) - 2*pow(y, 2)*sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) + pow(z, 4) - 2*pow(z, 2)*sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2))); }
inline double g_cartesian_02(double x, double y, double z, double t) { return x*z*(sqrt(pow(x, 2) + pow(y, 2))*(pow(x, 2) + pow(y, 2) + pow(z, 2)) - (sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*sqrt(pow(x, 4) + 2*pow(x, 2)*pow(y, 2) + pow(x, 2)*pow(z, 2) + pow(y, 4) + pow(y, 2)*pow(z, 2)))/(sqrt(pow(x, 2) + pow(y, 2))*(sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*pow(pow(x, 2) + pow(y, 2) + pow(z, 2), 3.0/2.0)); }
inline double g_cartesian_03(double x, double y, double z, double t) { return 0; }
inline double g_cartesian_10(double x, double y, double z, double t) { return 2*x*y*sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2))/(pow(x, 4) + 2*pow(x, 2)*pow(y, 2) + 2*pow(x, 2)*pow(z, 2) - 2*pow(x, 2)*sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) + pow(y, 4) + 2*pow(y, 2)*pow(z, 2) - 2*pow(y, 2)*sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) + pow(z, 4) - 2*pow(z, 2)*sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2))); }
inline double g_cartesian_11(double x, double y, double z, double t) { return (pow(x, 2)*(sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*pow(pow(x, 2) + pow(y, 2) + pow(z, 2), 5.0/2.0) + pow(y, 2)*pow(z, 2)*(sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*pow(pow(x, 2) + pow(y, 2) + pow(z, 2), 3.0/2.0) + pow(y, 2)*(pow(x, 2) + pow(y, 2))*pow(pow(x, 2) + pow(y, 2) + pow(z, 2), 2))/((pow(x, 2) + pow(y, 2))*(sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*pow(pow(x, 2) + pow(y, 2) + pow(z, 2), 5.0/2.0)); }
inline double g_cartesian_12(double x, double y, double z, double t) { return y*z*(sqrt(pow(x, 2) + pow(y, 2))*(pow(x, 2) + pow(y, 2) + pow(z, 2)) - (sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*sqrt(pow(x, 4) + 2*pow(x, 2)*pow(y, 2) + pow(x, 2)*pow(z, 2) + pow(y, 4) + pow(y, 2)*pow(z, 2)))/(sqrt(pow(x, 2) + pow(y, 2))*(sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*pow(pow(x, 2) + pow(y, 2) + pow(z, 2), 3.0/2.0)); }
inline double g_cartesian_13(double x, double y, double z, double t) { return 0; }
inline double g_cartesian_20(double x, double y, double z, double t) { return x*z*(sqrt(pow(x, 2) + pow(y, 2))*(pow(x, 2) + pow(y, 2) + pow(z, 2)) - (sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*sqrt(pow(x, 4) + 2*pow(x, 2)*pow(y, 2) + pow(x, 2)*pow(z, 2) + pow(y, 4) + pow(y, 2)*pow(z, 2)))/(sqrt(pow(x, 2) + pow(y, 2))*(sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*pow(pow(x, 2) + pow(y, 2) + pow(z, 2), 3.0/2.0)); }
inline double g_cartesian_21(double x, double y, double z, double t) { return y*z*(sqrt(pow(x, 2) + pow(y, 2))*(pow(x, 2) + pow(y, 2) + pow(z, 2)) - (sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*sqrt(pow(x, 4) + 2*pow(x, 2)*pow(y, 2) + pow(x, 2)*pow(z, 2) + pow(y, 4) + pow(y, 2)*pow(z, 2)))/(sqrt(pow(x, 2) + pow(y, 2))*(sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*pow(pow(x, 2) + pow(y, 2) + pow(z, 2), 3.0/2.0)); }
inline double g_cartesian_22(double x, double y, double z, double t) { return (pow(z, 2)*(pow(x, 2) + pow(y, 2) + pow(z, 2)) + (pow(x, 2) + pow(y, 2))*(sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)))/((sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)) - 2)*pow(pow(x, 2) + pow(y, 2) + pow(z, 2), 3.0/2.0)); }
inline double g_cartesian_23(double x, double y, double z, double t) { return 0; }
inline double g_cartesian_30(double x, double y, double z, double t) { return 0; }
inline double g_cartesian_31(double x, double y, double z, double t) { return 0; }
inline double g_cartesian_32(double x, double y, double z, double t) { return 0; }
inline double g_cartesian_33(double x, double y, double z, double t) { return -1 + 2/sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2)); }
